using Almanna;

namespace Parchment.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "comment".
	 * Generated by almanna-generate.
	 */
	public class Comment : Almanna.Entity {
		public override string entity_name { owned get { return "comment"; } }
		public int comment_id { get; set; }
		public int parent_comment_id { get; set; }
		public int entry_id { get; set; }
		public int publisher_id { get; set; }
		public int is_visible { get; set; }
		public DateTime date_created { get; set; }
		public string comment_sha1 { get; set; }
		public string ip_address { get; set; }
		public string display_name { get; set; }
		public string email_address { get; set; }
		public string content { get; set; }
		
		public override void register_entity() {
			add_column( new Column<int>.with_name_type( "comment_id", "int4" ) );
			columns["comment_id"].size = 4;
			columns["comment_id"].is_sequenced = true;
			
			add_column( new Column<int>.with_name_type( "parent_comment_id", "int4" ) );
			columns["parent_comment_id"].size = 4;
			columns["parent_comment_id"].is_nullable = true;
			
			add_column( new Column<int>.with_name_type( "entry_id", "int4" ) );
			columns["entry_id"].size = 4;
			
			add_column( new Column<int>.with_name_type( "publisher_id", "int4" ) );
			columns["publisher_id"].size = 4;
			columns["publisher_id"].is_nullable = true;
			
			add_column( new Column<int>.with_name_type( "is_visible", "int4" ) );
			columns["is_visible"].size = 4;
			columns["is_visible"].is_nullable = true;
			
			add_column( new Column<DateTime>.with_name_type( "date_created", "timestamptz" ) );
			columns["date_created"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "comment_sha1", "bpchar" ) );
			columns["comment_sha1"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "ip_address", "varchar" ) );
			columns["ip_address"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "display_name", "varchar" ) );
			columns["display_name"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "email_address", "varchar" ) );
			columns["email_address"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "content", "text" ) );
			columns["content"].is_nullable = true;
			
			try {
				set_primary_key("comment_id");
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
