using Almanna;

namespace Parchment.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "entry".
	 * Generated by almanna-generate.
	 */
	public class Entry : Almanna.Entity {
		public override string entity_name { owned get { return "entry"; } }
		public int entry_id { get; set; }
		public int publisher_id { get; set; }
		public DateTime date_created { get; set; }
		public DateTime date_modified { get; set; }
		public string title { get; set; }
		public string content { get; set; }
		
		public override void register_entity() {
			add_column( new Column<int>.with_name_type( "entry_id", "int4" ) );
			columns["entry_id"].size = 4;
			columns["entry_id"].is_sequenced = true;
			
			add_column( new Column<int>.with_name_type( "publisher_id", "int4" ) );
			columns["publisher_id"].size = 4;
			
			add_column( new Column<DateTime>.with_name_type( "date_created", "timestamp" ) );
			columns["date_created"].is_nullable = true;
			
			add_column( new Column<DateTime>.with_name_type( "date_modified", "timestamp" ) );
			columns["date_modified"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "title", "varchar" ) );
			columns["title"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "content", "text" ) );
			columns["content"].is_nullable = true;
			
			try {
				set_primary_key("entry_id");
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
