using Almanna;

namespace Parchment.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "entry_tag".
	 * Generated by almanna-generate.
	 */
	public class EntryTag : Almanna.Entity {
		public override string entity_name { owned get { return "entry_tag"; } }
		public int entry_id { get; set; }
		public int tag_id { get; set; }
		
		public override void register_entity() {
			add_column( new Column<int>.with_name_type( "entry_id", "int4" ) );
			columns["entry_id"].size = 4;
			
			add_column( new Column<int>.with_name_type( "tag_id", "int4" ) );
			columns["tag_id"].size = 4;
			
			try {
				set_primary_keys({ "entry_id", "tag_id" });
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
