using Almanna;

namespace Parchment.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "session".
	 * Generated by almanna-generate.
	 */
	public class Session : Almanna.Entity {
		public override string entity_name { owned get { return "session"; } }
		public string session_id { get; set; }
		public string session_data { get; set; }
		
		public override void register_entity() {
			add_column( new Column<string>.with_name_type( "session_id", "bpchar" ) );
			
			add_column( new Column<string>.with_name_type( "session_data", "text" ) );
			columns["session_data"].is_nullable = true;
			
			try {
				set_primary_key("session_id");
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
