using Almanna;

namespace Parchment.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "tag".
	 * Generated by almanna-generate.
	 */
	public class Tag : Almanna.Entity {
		public override string entity_name { owned get { return "tag"; } }
		public int tag_id { get; set; }
		public string name { get; set; }
		
		public override void register_entity() {
			add_column( new Column<int>.with_name_type( "tag_id", "int4" ) );
			columns["tag_id"].size = 4;
			columns["tag_id"].is_sequenced = true;
			
			add_column( new Column<string>.with_name_type( "name", "varchar" ) );
			columns["name"].is_nullable = true;
			
			try {
				set_primary_key("tag_id");
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
