# Plugins CMake include file
# Do *NOT* edit this file, as it will be automatically regenerated by Ambition.

SET( APP_PLUGIN_PKGCONFIG
)
SET( APP_PLUGIN_PACKAGES
)
SET( APP_PLUGIN_LIBRARY_DIRS
)
SET( APP_PLUGIN_VAPI_LIST )
FOREACH ( NEXT_ITEM ${APP_PLUGIN_LIBRARY_DIRS} )
	LIST( APPEND APP_PLUGIN_VAPI_LIST "--vapidir='${NEXT_ITEM}'" )
ENDFOREACH()
