using Almanna;
using Gee;
namespace Parchment.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "Publisher".
	 * Generated by almanna-generate.
	 */
	public class Publisher : Parchment.Model.DB.Entity.Publisher {
		public ArrayList<Entry> entries { get; set; }
		public override void register_entity() {
			base.register_entity();

			add_has_many( "entries", typeof(Entry), "publisher_id", "publisher_id" );
		}
	}
}
