using Almanna;
using Ambition.Session;
namespace Parchment.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "Session".
	 * Generated by almanna-generate.
	 */
	public class Session : Parchment.Model.DB.Entity.Session,AlmannaSession {
		public override void register_entity() {
			base.register_entity();
		}
	}
}
