Document: ambition
Title: Debian ambition Manual
Author: <insert document author here>
Abstract: This manual describes what ambition is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ambition/ambition.sgml.gz

Format: postscript
Files: /usr/share/doc/ambition/ambition.ps.gz

Format: text
Files: /usr/share/doc/ambition/ambition.text.gz

Format: HTML
Index: /usr/share/doc/ambition/html/index.html
Files: /usr/share/doc/ambition/html/*.html
