using Almanna;

namespace Parchment.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "Comment".
	 * Generated by almanna-generate.
	 */
	public class Comment : Parchment.Model.DB.Entity.Comment {
		public override void register_entity() {
			base.register_entity();
		}

		public override void save() {
			if ( this.dirty_columns.contains("content") ) {
				this.comment_sha1 = Checksum.compute_for_string( ChecksumType.SHA1, content );
			}
			if ( this.date_created == null ) {
				this.date_created = new DateTime.now_utc();
			}

			base.save();
		}
	}
}
