using Almanna;

namespace Parchment.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "EntryTag".
	 * Generated by almanna-generate.
	 */
	public class EntryTag : Parchment.Model.DB.Entity.EntryTag {
		public Tag tag { get; set; }

		public override void register_entity() {
			base.register_entity();
			add_has_one( "tag", "tag_id", "tag_id" );
		}
	}
}
