using Almanna;

namespace Parchment.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "Tag".
	 * Generated by almanna-generate.
	 */
	public class Tag : Parchment.Model.DB.Entity.Tag {
		public override void register_entity() {
			base.register_entity();
		}
	}
}
